name: 'Hello World'
description: 'Greet someone and record the time'
 github-token:
    description: The GitHub token used to create an authenticated client.
    required: false
    default: ${{ github.token }}
 sha:
    description: Sha to get PR for. Defaults to current sha.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
